# Generated by Django 3.2.23 on 2025-02-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gasstation',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
