# Generated by Django 3.2.23 on 2025-02-04 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250203_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstation',
            name='map_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
